# Obtener chat
POST http://127.0.0.1:5000/chat_routes/chat_historial
Content-Type: application/json

{
    "id_usuario_1": 1,
    "id_usuario_2": 2
}
###

# Enviar un mensaje
POST http://127.0.0.1:5000/chat_routes/enviar_mensaje
Content-Type: application/json

{
    "id_usuario_1": 1,
    "id_usuario_2": 6,
    "mensaje": "en la universidad, por las tardes"
}

###
# Obtener últimos mensajes de todos los chats de un usuario
POST http://127.0.0.1:5002/chat_routes/mis_conversaciones
Content-Type: application/json

{
    "id_usuario": 4
}