#REGISTRO PRODUCTO
POST http://127.0.0.1:5002/producto_routes/registro_producto
Content-Type: application/json

{
    "id_vendedor": 9,
    "url_foto": "https://manualidades.es/wp-content/uploads/2021/10/arbol-de-navidad-reciclado-de-50-ideas-de-arboles-de-navidad-con-materiales-reciclados.jpg",
    "precio": 15.0,
    "cantidad": 10,
    "descripcion": "Árbol de Navidad ecológico hecho con botellas plásticas recicladas.",
    "comprado": false,
    "tipo": 1,
    "material": "1,2",
    "nombre": "Árbol Navidad"
}
###


#FILTRAR PRODUCTOS POR TIPO Y MATERIAL
POST http://127.0.0.1:5002/producto_routes/filtrar_productos
Content-Type: application/json

{
    "tipo": [1,2],
    "material": "2,4"
}

###

#CONSULTAR PRODUCTO
POST http://127.0.0.1:5002/producto_routes/consulta_producto
Content-Type: application/json

{
    "id_producto": 2
}



###
# DETALLE DE PRODUCTO (incluye nombre del vendedor)
POST http://127.0.0.1:5002/producto_routes/producto_detalle
Content-Type: application/json

{
    "id_producto": 3
}

###


# LISTAR PRODUCTOS DE UN VENDEDOR
POST http://127.0.0.1:5002/producto_routes/listar_productos_vendedor
Content-Type: application/json

{
    "id_vendedor": 7
}
###
